import type { Product, ProductCategory, ProductImportRow } from "@/lib/catalog/types";

export const fakeCategories: ProductCategory[] = [
  { id: "cat_ferramentas", name: "Ferramentas" },
  { id: "cat_material-eletrico", name: "Material elétrico" },
  { id: "cat_hidraulica", name: "Hidráulica" },
  { id: "cat_acabamento", name: "Acabamento" },
];

export const fakeProducts: Product[] = [
  {
    id: "prd_1",
    externalCode: "PRD-001",
    name: "Cimento CP-II 50kg",
    price: 34.9,
    stock: 320,
    categoryId: "cat_acabamento",
    photoUrl: null,
    alternativeTitle: "Cimento Portland CP-II",
    catalogUrl: "",
    manualUrl: "",
    videoUrl: "",
    certificateEligible: false,
    leadTime: "Entrega imediata",
  },
  {
    id: "prd_2",
    externalCode: "PRD-002",
    name: "Argamassa ACIII 20kg",
    price: 22.5,
    stock: 180,
    categoryId: "cat_acabamento",
    photoUrl: null,
    alternativeTitle: "",
    catalogUrl: "",
    manualUrl: "",
    videoUrl: "",
    certificateEligible: false,
    leadTime: "Entrega imediata",
  },
  {
    id: "prd_3",
    externalCode: "PRD-003",
    name: "Vergalhão 10mm 12m",
    price: 58,
    stock: 96,
    categoryId: "cat_ferramentas",
    photoUrl: null,
    alternativeTitle: "Vergalhão de aço CA-50",
    catalogUrl: "",
    manualUrl: "",
    videoUrl: "",
    certificateEligible: true,
    leadTime: "3 dias úteis",
  },
  {
    id: "prd_4",
    externalCode: "PRD-010",
    name: "Furadeira de impacto 750W",
    price: 289.9,
    stock: 14,
    categoryId: "cat_ferramentas",
    photoUrl: null,
    alternativeTitle: "",
    catalogUrl: "https://exemplo.com.br/catalogo/furadeira-750w",
    manualUrl: "https://exemplo.com.br/manuais/furadeira-750w.pdf",
    videoUrl: "",
    certificateEligible: true,
    leadTime: "5 dias úteis",
  },
  {
    id: "prd_5",
    externalCode: "PRD-011",
    name: "Disjuntor bipolar 40A",
    price: 47.3,
    stock: 62,
    categoryId: "cat_material-eletrico",
    photoUrl: null,
    alternativeTitle: "",
    catalogUrl: "",
    manualUrl: "",
    videoUrl: "",
    certificateEligible: true,
    leadTime: "Entrega imediata",
  },
  {
    id: "prd_6",
    externalCode: "PRD-012",
    name: "Cabo flexível 2,5mm (rolo 100m)",
    price: 168.4,
    stock: 40,
    categoryId: "cat_material-eletrico",
    photoUrl: null,
    alternativeTitle: "Cabo flexível 750V",
    catalogUrl: "",
    manualUrl: "",
    videoUrl: "",
    certificateEligible: false,
    leadTime: "Entrega imediata",
  },
  {
    id: "prd_7",
    externalCode: "PRD-020",
    name: "Registro de gaveta 3/4\"",
    price: 39.9,
    stock: 55,
    categoryId: "cat_hidraulica",
    photoUrl: null,
    alternativeTitle: "",
    catalogUrl: "",
    manualUrl: "",
    videoUrl: "",
    certificateEligible: false,
    leadTime: "Entrega imediata",
  },
  {
    id: "prd_8",
    externalCode: "PRD-021",
    name: "Caixa d'água 500L",
    price: 312,
    stock: 8,
    categoryId: "cat_hidraulica",
    photoUrl: null,
    alternativeTitle: "",
    catalogUrl: "https://exemplo.com.br/catalogo/caixa-dagua-500l",
    manualUrl: "",
    videoUrl: "https://exemplo.com.br/videos/instalacao-caixa-dagua",
    certificateEligible: false,
    leadTime: "7 dias úteis",
  },
  {
    id: "prd_9",
    externalCode: "PRD-030",
    name: "Tinta acrílica fosca 18L",
    price: 249,
    stock: 27,
    categoryId: null,
    photoUrl: null,
    alternativeTitle: "",
    catalogUrl: "",
    manualUrl: "",
    videoUrl: "",
    certificateEligible: false,
    leadTime: "Entrega imediata",
  },
];

export const sampleImportRows: ProductImportRow[] = [
  {
    row: 2,
    externalCode: "PRD-001",
    name: "Cimento CP-II 50kg",
    price: "R$ 34,90",
    stock: "320",
    category: "Acabamento",
    status: "ok",
  },
  {
    row: 3,
    externalCode: "PRD-040",
    name: "Argamassa colante AC-I 20kg",
    price: "R$ 19,90",
    stock: "140",
    category: "Acabamento",
    status: "ok",
  },
  {
    row: 4,
    externalCode: "PRD-003",
    name: "Vergalhão 10mm 12m (duplicado)",
    price: "R$ 58,00",
    stock: "96",
    category: "Ferramentas",
    status: "erro",
    error: "Código externo duplicado na planilha.",
  },
  {
    row: 5,
    externalCode: "PRD-041",
    name: "Telha cerâmica",
    price: "1250",
    stock: "60",
    category: "Acabamento",
    status: "erro",
    error: "Preço mal formatado — use vírgula para centavos (ex.: 12,50).",
  },
  {
    row: 6,
    externalCode: "",
    name: "Tijolo baiano 9 furos",
    price: "R$ 1,20",
    stock: "2000",
    category: "Acabamento",
    status: "erro",
    error: "Código externo obrigatório.",
  },
  {
    row: 7,
    externalCode: "PRD-042",
    name: "",
    price: "R$ 15,00",
    stock: "80",
    category: "Ferramentas",
    status: "erro",
    error: "Nome do produto obrigatório.",
  },
  {
    row: 8,
    externalCode: "PRD-043",
    name: "Chuveiro elétrico 127V",
    price: "",
    stock: "12",
    category: "Material elétrico",
    status: "erro",
    error: "Preço obrigatório.",
  },
];

/** Linhas em branco na planilha são descartadas antes mesmo de virar linha de preview. */
export const ignoredEmptyRowCount = 2;

export async function getProducts(): Promise<Product[]> {
  await new Promise((resolve) => setTimeout(resolve, 400));
  return fakeProducts;
}

export async function getCategories(): Promise<ProductCategory[]> {
  await new Promise((resolve) => setTimeout(resolve, 200));
  return fakeCategories;
}

export async function getProductById(id: string): Promise<Product | undefined> {
  await new Promise((resolve) => setTimeout(resolve, 200));
  return fakeProducts.find((product) => product.id === id);
}
